apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: budpipeline-step-timeout-check
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 1m"  # Check for timed-out steps every minute
  - name: direction
    value: "input"
  - name: route
    value: "/internal/step-timeout-check"
scopes:
  - budpipeline
