email: noreply@bud.studio

cert-manager:
  enabled: true
  crds:
    enabled: true
  ingressShim:
    defaultIssuerName: letsencrypt-http01
    defaultIssuerKind: ClusterIssuer
    defaultIssuerGroup: cert-manager.io
