{{- if .Values.microservices.mcpgateway.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mcpgateway-keycloak-init
type: Opaque
data:
  admin-user: {{ .Values.keycloak.auth.adminUser | b64enc }}
  admin-password: {{ .Values.keycloak.auth.adminPassword | b64enc }}
{{- end }}
