harbor:
    #ENC[AES256_GCM,data:eCf1dokMuPyfeJoBYaolClyEkgsXK16qPf9OZHSCHpKSqfklNhva48BTn6k2DgQ=,iv:8wmLTb5icwfldBiiRbgaNR1ZsLQCIrDCUXJttuiGdVA=,tag:gPbWx8+LYCL9BtG93ES4vQ==,type:comment]
    harborAdminPassword: ENC[AES256_GCM,data:CgJxp8AWSjynutKq5A7bt5ua4tQKbp/EuD68mS+h0qs=,iv:oxyJDLxJeoM6MsBDX5/8Q7H/d9R76Q/C0RZmtGUVQ4w=,tag:CWsPHLpXjuG3alSAI4SmPg==,type:str]
postgresExtra:
    #ENC[AES256_GCM,data:VK7SwsAJNwar3F+6ZGes5q5YyMfZkjP7n85AC6n3lGzPWqGIhkrI4F5OFdHppuc=,iv:a55ZWk73jfc5+Uft0Cf2vyxTEignRGzWnbjgPrnBKKo=,tag:mxr1dlXwKriiCXYAthjPBg==,type:comment]
    password: ENC[AES256_GCM,data:7MY9FHrdCI6XvK/NQaH+wWgIP37waJw9LxQmBFFZ4QE=,iv:mQxJW+Kxvh+KgA8jRLMl/0OoBrMKGjE6RMBAwhaILwI=,tag:IQ+tC/J4lma2QlNbLkzoww==,type:str]
sops:
    age:
        - recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WTZEdzBLSlloNmRDVHQr
            UnYremhnRzVOR0x3L2xZN1RFNEZ4eU5UTTNZClpZclZ0SjlCU2czcit0bjhqZ2sx
            cnFOcXVleWRuWjhNU1Q4MHppeXB2R0UKLS0tIExPSnl0UTlKYVZOTk5UUXArSTlq
            RzZpR3BGK0IySWZVN3NEUVV2a1kwWGsKCwI/NaxuHBEfI5UoNFLz3S6PM5XyTpNe
            0THUX08PvdbfuhaG9xThuuTD2sxThTzXnaplLhPfRcchcwuVugIHDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWakxmSk8vZ0RMQ3RRNU1k
            d1VCL3BoRVFLbisyZXVhdjZ2aWpRTEtNc0VzCk5VaS9JSERjYzdDMWdPZ0psSVo0
            Ty9oZkpnN0w1NHRoNndhN1RtR0NtNFUKLS0tIDZrdWxDQzdhYWxPaG9JMkpTVVhM
            RURnNmdUNDBqU0g5NThuTDZ3dDl6QTAKHzh6Ls49Eu5d4CmiOliWp+XzCgVXH8cJ
            ZHBZtSKbRQrKRggY4CnEAtbDzcU0zXxDX0EHy52vfUH72Jh31Mnnmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ueu6gg5sgnvlnyk0u8zfyvpgrgja3g0xxdp9whegwk5rqlu42gjsveqrjj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM0lTT296U2dYUXpXZEQ2
            dEpPNzlXVHJaOEtsa1VpeUpZVjhCdVBWclJBCmhNU0QzRURhcjk5bGFjWGF5ak1T
            NVZveFFhWHNGU0NremRmd25KNUF3SFUKLS0tIHhGYk44eGdGUmdUQzJYWGU1OEQw
            OFd0QTM2NFJvL0FpWi9IT0g2K0FZeXMKjpX4OAC/9qA+HuRDFp7ZPfp+NAkFCx30
            RB8PMt887RKI5zPpsJKW4iccdq2ePsRZ7hJZ/RKEiShDFFSO9UFxww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1evyhf8qvcvftzhrznv65a6shag2r05wnzmfkfaad5l66ztztv4qsh7f23k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSjFpOEk0R083b3BYdW5o
            a2VWNHBGMUo5cmY2ODBkaW1pUWhlOVhleURBClZyZ2ZyKzJLV2pTOWVtN0xPcUpH
            N3ZJQnVZSS9vMXZOUXFKbVRWOHJXMlEKLS0tIGtCQnlNNzl0NzhLK3puNHJ2cjRK
            ZmRCOGxZWXliZzVTdzB4NjJJWXYwUmcKOMe470nruLJy8O8XB2uLi6vJvKfM3ddI
            XN5fM78dszat90hGNU/xtDxPo3I5HZH7iT2RgfjW/hioVPy6vRXP9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g22rh8x48tanpl5pq6pjrpmslnvv0e3qcm6w7dghhe8cnl5y0evqu835qm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWkEwNlB1YkRBNnlpZGZY
            b3M4NGdyN2o2QmVpSkNwcmVIWXU1YWFJdDFRCklWUEJEcFVUL0hYaEQ5YTBiYmpr
            YW9yejNKdEptODdUeWJYVExtZUtDRmsKLS0tIGhPWEZ1cHJSU2NpZUdWTjZWMkpH
            ZlNjZlp2NnFvZjNnTy9ReTFsVUtSQVUKUqsMfQ39XhRMdSIDO1+WOz8YD6qKdrOJ
            Jli/qsJr3lQptEOrQXtxOh0vPa2hy1rZqyW/LRcTkQGaU8hKVdc5kQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age138ut93gvvwkaudl3wxtwn8z9e50ptuhe2yukg6vhwcgncxpplpsqtmhp7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYjJXUWZJc2hEd25lYVo1
            eXNrTDhsNVFJditybGdEYkVFbHlicWNBQkRNCmluZ1BraHg5aUtUKzdYRFVjUlVM
            OUVrUXFXRVg2YlM4dlo0TjdQR3pRd1kKLS0tIHNKUUpTSDBXT0xNUEV4SzNqTGZI
            Sjh1Slp3alc4SERXSnI0VFBuSDVONUUKANXADy230sRfJloUH4JZKSkofvnsdDaD
            Pdp18Bw14tHqlekqxfgCuv2PomMd/AxnO0LkCIlMro3wPfhuW4Uw/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-22T08:57:05Z"
    mac: ENC[AES256_GCM,data:MhqFPxjT0nZhngcxqBAXgS+W9ixQXSKTpKqhLK+vRvBsvrstFiOLGMQ2s4L9BAxr9ybJ/SgR2pqLwn394GOUlpSXhBr10UluZqZEL26hG0a5CfZfv4HLIlSImda4A3FkBVDHySIevk6+MkQ2FoojYBu0lO2UO5iNmHtEwU4FKFw=,iv:/Xg2V3Md1ep/wv+Jhiu8eJZNZb1oSvlF4vdk1aIVxvE=,tag:WW9WfeIU5VmxV9KHJbdqqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
