harbor:
    #ENC[AES256_GCM,data:eCf1dokMuPyfeJoBYaolClyEkgsXK16qPf9OZHSCHpKSqfklNhva48BTn6k2DgQ=,iv:8wmLTb5icwfldBiiRbgaNR1ZsLQCIrDCUXJttuiGdVA=,tag:gPbWx8+LYCL9BtG93ES4vQ==,type:comment]
    harborAdminPassword: ENC[AES256_GCM,data:CgJxp8AWSjynutKq5A7bt5ua4tQKbp/EuD68mS+h0qs=,iv:oxyJDLxJeoM6MsBDX5/8Q7H/d9R76Q/C0RZmtGUVQ4w=,tag:CWsPHLpXjuG3alSAI4SmPg==,type:str]
postgresExtra:
    #ENC[AES256_GCM,data:VK7SwsAJNwar3F+6ZGes5q5YyMfZkjP7n85AC6n3lGzPWqGIhkrI4F5OFdHppuc=,iv:a55ZWk73jfc5+Uft0Cf2vyxTEignRGzWnbjgPrnBKKo=,tag:mxr1dlXwKriiCXYAthjPBg==,type:comment]
    password: ENC[AES256_GCM,data:7MY9FHrdCI6XvK/NQaH+wWgIP37waJw9LxQmBFFZ4QE=,iv:mQxJW+Kxvh+KgA8jRLMl/0OoBrMKGjE6RMBAwhaILwI=,tag:IQ+tC/J4lma2QlNbLkzoww==,type:str]
sops:
    age:
        - recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YTFkcVhNVVlsWk1zblJM
            aVBCNmRTU2twei91cmZ5V3hJU3Y1TjNuRWtjCk9tdUQ1YTZyT2oybm52R2piUFg1
            TDh6Y051YllVWkFTNUhqbWlIaHFtam8KLS0tIEk0V0wzeGkrb0YvMHpvbFlLUmUx
            MG8wdlZnYWRWQkNuMUxmNENWQTFwVEkKcfI1mZ+nRFc13HBoM1uG0YyQHHD6dJYU
            fO4GR1QspUGVHEFUBDO8qtSa4HmgUPf+6GAbelokJXupv+A9rocTOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSlYwWmlrbE0wZGt2Z040
            TmpxTm9hMWx6VEFGbURtSlBXeERHenJKT0I0CjBpMmYrTkhoWUpQK1RLTytCUU9Y
            SFRIaWcwTmxBYUI3R2xvdWNOSkxIK1UKLS0tIGJ6bXNMTHh3eHVQV2ZZTVJ3a1Nq
            YUo1M21Ia0xiTVE1ajBWTk1XTGd3UWMK9SLpPTUkyBoMLfI0zIRcCQP9nBtmrUws
            B6xO6GJwJn68jzUgkmYYl2BJGb4/kVmemxI7X+jY0SOFLUtarl5mng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ueu6gg5sgnvlnyk0u8zfyvpgrgja3g0xxdp9whegwk5rqlu42gjsveqrjj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSWh4ZDNMZUdkdmE4MGFj
            YU9semJGeXc1NkIyanhVdU1UMW9GWjBOampBCnFmaWwvODVtc2lZVVdHdVlSUFhz
            d1ErZE81UEJlWFRwWXlCRm1yVEdFSlkKLS0tIHpSWWVuc2puZWdGZ2RiWWYrNysz
            OWh3RjhwRTJWQktJOTg5YkxjSE5NakkK9urHNWLoX02Inb1A+6SomnolcwAXzi07
            i6PxFvAS6F4VRCnblkhxTXB+X4aMEM4O7Oe4DgXmuygRr+1bpNARSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1evyhf8qvcvftzhrznv65a6shag2r05wnzmfkfaad5l66ztztv4qsh7f23k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTjFkVm52Y3MwUklkOHN3
            UThFSXF1OWpkcUxLc2FVcThxWmEyOEpFTENNCmdJY3ZhZjNYenM2eFhXU2hRbXBi
            NnNDRmhyV3dPckozYXd4Y0NaQ1FaVHMKLS0tIHBMSFc5UVhrdXZZVjRaMU5TUXBy
            N2d5MkIwQmtlQkVoTDNaOE1JeHI3ZVEKrgmVDNjb6Qxa7x80+P8anW2CAx5gB5zc
            9ar1Y8HebBhTYZo/DJNrdESs3pyxaPncdzmC80EwBa7t4v+ikQn7/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age138ut93gvvwkaudl3wxtwn8z9e50ptuhe2yukg6vhwcgncxpplpsqtmhp7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZEh0YXFPTHVPNmMzU3d6
            cURTbGlkemFReDFKODVMMG5PeEw2M3h4cFFBClNqR1hhcUk4bGhwZHpFQ3dYNHQw
            SHVPM0lLWnBhV2ZqdXlkQWNld2lQUVUKLS0tIHI4dklCS2hMVEU2bkJJY2ZmQ2xH
            aHBMZ1FvaDJmZ1pOazQxRG9FQngyQUEK7ysqNN5pEmDGIw4iKpYH5NC/DIjr39qg
            v+tgotRSHeifFI0FdyX7xDDRm9O+z7Xc+0eA5AkYaPMsXbXIGko90Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-22T08:57:05Z"
    mac: ENC[AES256_GCM,data:MhqFPxjT0nZhngcxqBAXgS+W9ixQXSKTpKqhLK+vRvBsvrstFiOLGMQ2s4L9BAxr9ybJ/SgR2pqLwn394GOUlpSXhBr10UluZqZEL26hG0a5CfZfv4HLIlSImda4A3FkBVDHySIevk6+MkQ2FoojYBu0lO2UO5iNmHtEwU4FKFw=,iv:/Xg2V3Md1ep/wv+Jhiu8eJZNZb1oSvlF4vdk1aIVxvE=,tag:WW9WfeIU5VmxV9KHJbdqqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
