ingress:
    https: disabled
    hosts:
        root: bane.tsnet.bud.studio

deploymentAnnotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"

storage:
    budmodelRegistry:
        size: "128Gi"
minio:
    persistence:
        size: "128Gi"
