global:
    ingress:
        hosts:
            root: bane.tsnet.bud.studio

ingress:
    https: disabled

deploymentAnnotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"

storage:
    budmodelRegistry:
        size: "128Gi"
minio:
    persistence:
        size: "128Gi"
