microservices:
    keys:
        # Get api key from mcp foundry service (https://mcp-foundry.bud.studio/)
        mcpFoundryApi: <api-key>
    rsaKeys:
        # tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
        privateKeyPassword: ccHGQlmO8HcUqOjU2kUh4PFmoSuxzY0Z
        # openssl genrsa -aes256 -out private_key.pem 2048
        privateKey: |
            -----BEGIN ENCRYPTED PRIVATE KEY-----
            MIIFNTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQ71tFtiF/EHG9VgeR
            JMVpIAICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEFuQW+IInEl6JXth
            29iQxgMEggTQCjiu3UJjFdOR4n27z/Izj15xpcIyNGPF3KexqHvqNJJ8kY0qEaqy
            9wLLb/LXpwBwCCMSbo2WhXrmn5VRrzNfBcSz3FAjCwkxSleLC97D1gGrxSqlnh/T
            GvrB9ceyeTIOavEHDczJKFb4McSgVHCrR4Vi9r4pI+A147aIvrZiXb2LMX83Equl
            DVsqC0SqQg6CAE4VImwD2NYIhL2dxi7M6W/eweVRydcCAHHuWA25t8tjW45zpmTa
            V5RnXIh1KP8CWjwGZS48b0l5A1dN/PuRZsgMYeo3a69J2OHaaZVm73pBsPhdKzVd
            14AeCwbtmQ0wpNKdsJa4B0A2W4Ks1JDEQ6EWNtKqS6y1dzkL5gwq3aZ+nXNRhtyI
            aqVK4SK7ddN2jyM4AGIm9cCG4mXyoE2Gxr25C+lsZxfWykAnRUtpF3gn65zDWnjb
            JQfqWpiHnjvhBY+pnbMHS5nlYGZR+7leE8VoOzgPqoDO/3BF+934ls7gatBYQXld
            GGd6qYNGKxcK2RR7ijWeqWDCGqr8pnCPM9xkI7+kC+NoHZGM6cUbz9A6zrR6wS3y
            xDOmtFZp/YE6TxsWaa8K30qXjJkZtSnPcyl2blDnZ31bFsWyORT1hnuZt5BuMybb
            SuWsKM7iMAoAdD47wliUMxkfwYCoyoEzkCnSurhSxmJ2+hOqMyZ1/85ovwljJY7t
            Y7vJsJXmp37nsXtGw7M7bklO3IwWHij/1tDLGG4Cpw0E5DMndOTWWlo7w3enHWuQ
            Y8vv/JNBacKgI2ZnmjWKgfPCR9wgt4RfJah5GQw346e6fNw8I7YNqzkjRRkVyxR4
            3MvEhHY8u6OxwQZFGK73UDoWHN85Q5KAz+tp9OoyHjexB42OVCGgVqHP0blaWrxp
            6RPgLq5l3akKBDr21MeihJT9EPPjV2/7V6dWjEpRBFUAWFQ0NjAvtIOhIavgSEcS
            TCvvdjrFs8vUczqEeN1H03ZI/0KP7jxTLpmWGLZNyYJG7R7cuqA5WmDMkL+Kp+BL
            Y4E2JKqCp+GiNoEUGMc6RGfc2uCRPkCLLursZ6oeKOBAyquE6Zhuq6Afknpc0z4r
            GcRgsWCy20aU1NZ9NA1IRiHFJtUc4kxtyeinIpmWVqrSoKXUBN3lG6EfEVsuAGll
            Ewx7yrNimJeIj+vA+ds2Z7QjQB+XVBHSgjdCyQ4P6E8gqWZ1tSdRhJ3Y2UuOSnuP
            y/DvQbOnVrIfPjkHlhADE9Mx502VBeGnhKwoY7PJxlwBWv6N84B1Tu+DYuh4Y4vr
            s5hlt8plLtBX0Loswc8IhxPwXVijBgqlUa2n1z+TeDajVfFGJCDbOhkdYcon4ia3
            eK9WQIaBWML9bz7+CXKtJZld5c3q2QavUBvbykQt3A6XxZc8JqBQ4oigbDGbcQG0
            82OWFlyImk+8zZ1+vboUf/rW5h+H2biTbdr8mHdOq2PADcw1roCuMC63otX6CgtQ
            u7U2HbwjqUz6kkLY2FWb+2/GFsQIXEm+kyo8nnsmFCOxCigN5iS/gjM3h28ZsEnV
            GnWdYgW434seFvHAd5YgCZWh4JRLj2Dmrr6wN3sjMgA/KTPKuvyoeANn9rB4s+g2
            2mzqQiEkuQdJBHPbeYDzFSmwV1MbUrQGed4mjEN/BB1VvanmW5je9UY=
            -----END ENCRYPTED PRIVATE KEY-----
        # openssl rsa -in private_key.pem -pubout -out public_key.pem
        publicKey: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlKXTX2N7bKJabgMdT2m5
            xhmVW+td8KTS3sqMjHJvJM8pJ5qucuqIk7n9fakrJNScdtMMi328F6oK/9PHiqG6
            aaMa2tbuPn7IRluMD0QwWIP7i5kZeDxB013Q/uvkGEYXR1t8aXCwb+RqeeUS+E26
            EZ4KkwWv/NqLGEix2MdmpzFhOpcMgVtVsggKrgv+KcL+nMXGiPp5gDYc5/q2cUu7
            t+pJqo2DehtcQse6b38kZLhr7naKZ7WCRi2guMp01VzaDDzY6Vr1fLK5BYkLLDEe
            27Wjtgwmfea3WlyQLYgYreffaT73xJhLDqFKaCT27F+sQIOE8MI0VER0bR8gsaWn
            NwIDAQAB
            -----END PUBLIC KEY-----
    budapp:
        env:
            # tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 64
            JWT_SECRET_KEY: 1Fb7H2S7o4G5oUAcfsDFbrfJ3Y5XmULbnbanvF7BsyBiq8lBekd2JsWEK6TQNkJn
            # https://huggingface.co/docs/hub/en/security-tokens
            HF_TOKEN: <change_me>
            # https://grafana.com/grafana/
            GRAFANA_USERNAME: bud-runtime
            GRAFANA_PASSWORD: ZvJgAPzlpUFdihc9a0fgtmY5c9inzFho
            # tr -dc 'a-f0-9' < /dev/urandom | head -c 88
            AES_KEY_HEX: 5b9b01f334a2d982dcc0b56956b70e5a673165a827aa9a0f8e6df5ca61ecfa6651e655105ac2be577ff34038
    budnotify:
        env:
            # tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
            STORE_ENCRYPTION_KEY: CFMryQwA8pSTPcx8nnueChg3b8P9tdH4
            # tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 64
            JWT_SECRET: E4gwGDsrHSddakY0rtzEE7LA7oqZIQZvxdGvYZdynisgFnhmeCWFNF6FrBmOxZH3
    global:
        env:
            OPENAI_API_KEY: <change_me>
            # tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 64
            PASSWORD_SALT: pL4eVOkzsLEKc25T69UCvjXvK0BxgghwzSpEE9wBbUMNezEODv0s7tWcrhEeQyCh

            SUPER_USER_EMAIL: root@example.com
            # tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
            SUPER_USER_PASSWORD: LCMSaOh2M2zMtMim0JOD5ctmyPFeVVNG
keycloak:
    auth:
        adminUser: user
        # echo bud-$(tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 16)
        adminPassword: bud-oA6ptv%Yatgp?VgH
daprExtra:
    crypto:
        # tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 32
        symmetricKey: I6e!yKxURFzBcV4!3nJmlINrqFbGx1S6
        # openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out rsa-private-key.pem
        asymmetricKey: |
            -----BEGIN PRIVATE KEY-----
            MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDVJ4VIsq7Op4Mw
            wJFJsiIXvl53s+f/VtbAXtgkw0b6hnPMkBomdA9pcfp1EBk4mY6EbJhfoy+1tBuN
            7Crdqr8906uZWbsSKyYq3t1RicVqKCPzXULOd+5NTZ4nT4ZyQqgU/UufXyRld7LW
            VFAifJFxhxcd1MZj3avkwohkr8QBIL3n42c1B7Jwavi3ueOQr7UhdNLCEjXuwy5r
            7bapU7vFeYR+iY/0Y4Xs2J1+3H3P+7+XemDyV6uS3rxCrb9ArbtVF6LDrbyn7AVc
            hFvGV2rOtaN2CApcR9Ch5DXCtPDn65kTJYmzFAddJp2wR6+/PLeek87/7eNEvRRr
            MZSKdI6FGk6HXsitAUGy5htI2Wz49uztbXqFMTT7kqAc5HwKH0cDXYQQD83lKVqS
            yetZDjJ5xY4Qx4caJigaDG/o0BQWCWYM7lfo3033QnMnGPSzMkLfN4RmZe+jGPgO
            K0ch8E2APiMiR+N2Ku6chz1VOXFyIodjjhhjmLPnCK7tvZRR84cR6Mn6zI4HfCb3
            05CQQJKLQxB/8DD6XvesQn13Sej4u1kXquDYOXWiOrR7i+5srZ5LrzAYSmA9Mteg
            VIe2h5I8WEHre86SYlNOANSPRoayJMqU2ax8+K/1o0siS+TnZMOmGUjcd/cRdB0J
            HwBj74F/drNgrmTYEZhuMcnnjtiVpwIDAQABAoICAFrrGozhunJnPSwkV1Rp6OTb
            zIueb0yYi81OJz+3E6V0iBwvMxhH1PMTLNOV5EwiI4oUkAHrJ0SH6GDm5XnbhOso
            SD+G6KZdRVBv81L+Qvh+2qbJlt9ehITwoI7/+sbt66fYStNVz76ACgYlvHCZVahp
            CNEumtiqCtHusCLSXfZlMtugQbt65v/QgPpNDeX/LHFy1Rr2jY6kLj7XDFy5XJRk
            usEGiCKj+NIHq1YbUobOSPChwIxeHM7utrpyReuerxMim8h/aMLvh3Ho+wRk8Sfu
            jiSgVVr7PuBu6Qd+CmvCMG7cShnaZzGycPxp92rIyUGYpmi/3XrKc9UtNsC/6rHP
            sBGGXuFt+Bx6U8bW36T0ZqvafkkYwQftW9nCF19l2zJzIk5RQxSDV6PbmgEbgvBZ
            FSTiBlW2Hwl/MBTQ/Sy4Tu7Gc4bNzrM+nSAVgaPil2pqQpLbVPbgUoi1V6P5p9+R
            vwm2PDMegvNGF5JwTWNHZqUJXhYzSc/flSOhFzg1zaJHBAP1g/rflbYOQqz3Xl8i
            PHquHysHFdODYEegUgBz9Qvf3Tfk1q3ep/JLMApqo+wcmjtrh0ksKEloANZOTBWR
            DCNvvAoVR6JrVY/lWhNFHBE21IabeScMW0DU6uRYgqFp9fRxjzx3MTif/qt0AfpB
            zYT9BL0p5vrSAbDRUGxBAoIBAQD7YGX0/zz4QxS5KdYHiR8JuQDO2r4g20SPKhK1
            oIuZgQhEwrzGhlAP8P+HNoxXT1k8mBsztyLlc/yonJLUvW8jg7YnwmNUygDFVCiH
            3ZJsq/4dXM9HLxBmXHgqupGpweUmfMHDpA7L36PrXLBjxP/yY+BHXCFzNxlee9vH
            zs/RoB8nWJfKGrixFhfLf/ZKWYnsB4cnLlN3m7MO4tRbSYDE/ThEdz06EhWGdEz5
            2XhlQnzl+z7U4Wn9rYGpyOlFIjR32cpLrvcPtK3u81p0Jynpm+JuIibTUnf/y1kK
            EIrppur0DIAVs3+d0tvQobgpnia/N8Tki6MRFRSK+PCRPnXXAoIBAQDZEydqsu3p
            cNAVBTgJ29SdVL5vUCmcl+i8w52EEgsaeVOPGuBXGGJ4c6NP6cfiKsLw6FnYgPjg
            8RLDxIABuxSF1thUPFlL0zSorDPu6Ass5ZwXV+D9FuS9nvcFp+8C6A2DwzYH1EfT
            MsfOWR7Rrq81hjZw/3s5ZYzLufkoiP/TDdT8i5sm3OBjuQkrR4mfqxJLezeoaNyo
            hzraTE8TreBFbstfXobQJawfLhhz/GV31ICEiY9Rm7iQMvO2uLyG3KUNbgEsUY47
            sNotUSQqEctPpbEX1uuHmFWtlqImvjS0VxX8holDEzc5kHTWJr1U5zDA75O0zlzH
            Lu0RBmJsBESxAoIBAQCEqNjltJVehzg2h6eWDn08yk9s2u+fs1e5HgEFrRY/CmNs
            tkCdnGBAKXUQzG6/3PZBDhy87BcUdGOQMCEk+FvgqC/HR8TYCErj2IgTO5F8nD/d
            Cw+wh1vmSUJ5ekBJEDR4XTp8nuXYHcwJ9752yI4yQxcnUa2tehR/UmooRjJSdGg8
            gXqJhBSYEAq6sGsvzZUF5OskeERASQD0CCz9iArW6rN5HlxHeye070d4S5ZIChCT
            5kXAXr1qzNgy2/6PJ3/9CAjEbC+iMD3ibrb7uXda+5NBf/BxcYI2kgAJWbWVnSs9
            ZCNsUHA2wAKVVeM0w2u7Whkka7TA3RkcRkfevtG9AoIBAEOrUuhSKxRQlK1Y2SVJ
            oDgDiPIOXUpxmJ3vpRTcwxVXqRK9YB4GffvqoIhy6lq41dhftlJlsi/9NspMYVMo
            zLcESJ/JyFR43LuQIwhg0csHMOed/4cmMdxix8K9nSaczEm8+wTpyhIujFbpNVBM
            UlYvJp2HJxS3cXK44NEgFA/pCfJIWu98f37W2eLiBCcAH03kdW9McS0gKtqOW0BZ
            PcanSULLpt8QP13g8sKFdeQrHH00nLbmAl0BZTQa1rp74gATwM3eBqbY9MqXttxe
            e7CyiEhUOUwl0t+wS5AkTy3A0BvOnM+KF/cb7zArF252O56JkNQWWJnHKSPbh6cA
            laECggEANnf4QE17wpyYTcJlxiuTKbhkf5Pcsh9WtnaymCnVsgGcqH19/NkDdQB9
            Wmnx39OeZ8P/4FF+t6WVmcfA/EnnaqJuBGfP3surLEN4XLQAV+GKLMDjfRk/D0ig
            RMFtb/lN/aEVvW6vFrW5BVayNFZsxv/c/kWh0Hkti0ALlhHg7u+NzdrQy3TzKvSE
            I4fOMmunGyKZuC2BtSXD6rb/bTw//UiaUl334jenhcukCQsJVeQgJ6CAw5TLjTZ6
            SS210/F5ajQQ6atch5hV9ffPvsFpuIGKdW+Dmb4lynVXmLUhPaDn8NuTdJEI0i9w
            98aw0yFJFDe4dXlpv5zgLyZJDBMGZA==
            -----END PRIVATE KEY-----
minio:
    auth:
        rootUser: bud-runtime
        # tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 24
        rootPassword: zLtczNA8EJ=ge2sSHE?xmZKy
novu:
    store:
        # echo bud-$(tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 28)
        encryption-key: bud-gUXY7j0k14yinhZm4w!eSqBGlexz
novuExtra:
    email: root@example.com
    # tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 24
    password: fomah4OiKaesh6azChoh7uoM
mcp-stack:
    config:
        BASIC_AUTH_USER: root@example.com
        # tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 24
        BASIC_AUTH_PASSWORD: d7T%wlDmV8J3D4zyv%yPEI7v
        # tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 32
        JWT_SECRET_KEY: 3OKnSQZUB3?HU6QwisONaPz2iXD9b56%
