release_name = "bud-dev"
namespace = "bud-dev"
sops_value_paths = [ "values.enc.yaml" ]
value_paths = [ "values.dev.yaml" ]
dependencies = [ "cert-manager", "cert-manager-issuer", "dapr", "nfs-csi" ]
