imagePullPolicy: Always

ingress:
  hosts:
    root: karthik.bud.studio

microservices:
  budgateway:
    image: budstudio/budgateway:nightly
  budapp:
    image: budstudio/budapp:nightly
  budmetrics:
    image: budstudio/budmetrics:nightly
  budeval:
    image: budstudio/budeval:nightly
