imagePullSecrets:
    - name: harbor-bud

ingress:
    https: internal
    hosts:
        root: "dev.bud.studio"

storage:
    budmodelRegistry:
        size: "1Ti"
        className: nfs-csi
    budevalDataset:
        className: nfs-csi

minio:
    persistence:
        size: "1Ti"

microservices:
    budadmin:
        env:
            NEXT_PUBLIC_ENABLE_DEV_MODE: "true"
        image: budstudio/budadmin:nightly
    budcustomer:
        image: budstudio/budcustomer:nightly
    budplayground:
        image: budstudio/budplayground:nightly
    budgateway:
        image: budstudio/budgateway:nightly
    askbud:
        image: budstudio/askbud:nightly
    budapp:
        image: budstudio/budapp:nightly
    budcluster:
        image: budstudio/budcluster:nightly
    budmetrics:
        image: budstudio/budmetrics:nightly
    budmodel:
        image: budstudio/budmodel:nightly
    budeval:
        image: budstudio/budeval:nightly
    budsim:
        image: budstudio/budsim:nightly
    buddoc:
        image: budstudio/buddoc:nightly
    budnotify:
        image: budstudio/budnotify:nightly
    budsentinel:
        enabled: true
    budprompt:
        image: budstudio/budprompt:nightly
        env:
            LOG_LEVEL: DEBUG

imagePullPolicy: "Always"
deploymentAnnotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: true
    keel.sh/pollSchedule: "@every 1m"
mcp-stack:
  mcpContextForge:
    config:
      APP_DOMAIN: https://mcpgateway.dev.bud.studio
