imagePullPolicy: "Always"

ingress:
    hosts:
        root: varun.bud.studio

microservices:
    budprompt:
        image: budstudio/budprompt:nightly
        env:
            REDIS_DB_INDEX: "2"
            # BUD_GATEWAY_BASE_URL: https://gateway.varun.bud.studio/v1
            BUD_GATEWAY_BASE_URL: https://gateway.ditto.bud.studio/v1
            LOG_LEVEL: DEBUG
    budapp:
        image: budstudio/budapp:nightly
        env:
            LOG_LEVEL: DEBUG
    budcluster:
        image: budstudio/budcluster:nightly
        env:
            VOLUME_TYPE: nfs
    budgateway:
        image: budstudio/budgateway:nightly

storage:
    budmodelRegistry:
        className: nfs-csi
    budevalDataset:
        className: "nfs-csi"
