imagePullPolicy: Always
deploymentAnnotations:
  keel.sh/policy: force
  keel.sh/trigger: poll
  keel.sh/match-tag: true
  keel.sh/pollSchedule: "@every 1m"

global:
  ingress:
    hosts:
      root: sinan.bud.studio

microservices:
  budprompt:
    image: budstudio/budprompt:sinan
  budapp:
    image: budstudio/budapp:sinan
