apiVersion: ENC[AES256_GCM,data:klE=,iv:U3owSxS3JlNCTqN5u3pHm5xXohqAYFP7UgEOpYzLlgc=,tag:EdKn6K7bgSapgkhUUXgLQw==,type:str]
clusters:
    - cluster:
        certificate-authority-data: ENC[AES256_GCM,data:69drN1Hrnnbarz8d2Y1CCqU7i1ZtgFg3rzKl198huPU/NwI89Exx+K1hbUPT4NaoLjCJ+0EWRGSOyJKe6lFq/wJXGIApI/w3Uzxw9vWWTy9BiSkKGW9p2qDnK5dGvXXyfvZ8m1B9r5wYIohxp8gJ1kJKuB24Xtndb/QYhQqTh88V4Opmmc7U3I1t/Hz/d6E/+6JS2iq1+uNfChmoC/+KqxIGvobkgpKe+jft58IJps6yImFOHTrZwTxzhe3kTA6NQn4ErYlBCpJ0stML7PjQTw9qGUArvEoAy5m4dlZ9QTekfh7yxpGBzi1QmZgoQEmKdTp1l6jsLPHVHBeWsEk3lk/0Zb5hSI9bfaR/b9ND1UWm/vLwod5e5yrM4lM0mgQEpgjg7vT5CWzWJXLbiaDg8NJY1t4m3glT1Wt0+KGYQ0cn7HDZqaqG6MhMzaya3yl8eMxtGYgnedh3afyP59uvRu18FgIs7XJYhX+q/qcy9OUi2AAEgjLOA6964+GP4L5WFxvvTTgoO2AWjoWSaRkuLxnwhmQboZTWL/lzxbxP1C6AdgqOZntBeU1tJv3VT+vUummvboyAGNdr/X335M0IZuMIVO17KYQXVg6Lneg7Fg8fGtqP82KonwWgOShGRfY8v2mHWSEXKL+pWdKzDiAQBKbtyaOfE9JQXkTBKiQlUJMf7BTGT5Ns1cjzNJjXJYJW1aSHUpZkLyYwXOAY7EUvuR0fjpS9yqJiqjLpeHUtg7TyHVOVhzkLWRFzxWU+aSasdO8r5IRmO5dhUUJ+mfKYQgNI0Tm3djiYxLUaORKLTE3uq6V3bq5tdnPHi4VdrFXtvnAVDuJ/Sb2p2HoN21ca7vdO9WH2V4emqbbAdXhTBD2kRbF71bZF3r7npcbmLIP8WTWavzi2QZOtreMHjoKdo6G7fHI4dvszNPVHqQeTIl5bvgimaTnreMHgDDNV7u5dL1+iyozFXU6hsVzWXKpRU65nGt6nQgjp6vsRh+mommqu/DP9gds1xw==,iv:guvNrC7OAx+eU/rHeqNCgTvhZHp7dlzjCo8LZsqiQ94=,tag:h5FFmuJx+XnutY0QHmIOfg==,type:str]
        server: ENC[AES256_GCM,data:7LEWUBhZlla5Uz43grOTa+2Ilz17sL3f,iv:EMA5KcCfOrbv7YDL+AEz8uAASN8YDqiuCY/D3AOnD8k=,tag:2YOdgCV3Xwpt0ZbdU6My1g==,type:str]
      name: ENC[AES256_GCM,data:gr85gdXr6A==,iv:csMAsm7OLudmzbxaIDfaiF5fk/rfjm/ajymF7uxxtS0=,tag:0aO04JO589Z/MkRDP9t53w==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:EA9BfJdz0g==,iv:6uR/Zgs5u1A0TwwKpYMa35PpPfXwI4QogtQxzRjH8zA=,tag:Do6/qZR1eg2a6PQprHMIKg==,type:str]
        user: ENC[AES256_GCM,data:5e//ApuVFw==,iv:4bmWZniRGx78vvmTTJl4hcXKIJpXO+TWMqbADaRmpyQ=,tag:aPZQlcU1TCyW7vHoY4/X1Q==,type:str]
      name: ENC[AES256_GCM,data:LSdp7yQwEg==,iv:QETLhMLhTiOPojOLDeYkTO4nMUkYXeITLFNYVhLmoAo=,tag:CfTttFhpFCsCnTI5Sg9uCA==,type:str]
current-context: ENC[AES256_GCM,data:X4EL1eP/yA==,iv:uYP+PHvJMZMce3pTbVf6t+TCmtLWO1120AhPsMH+QTg=,tag:pRGzj1IBWSC95xeH1kButQ==,type:str]
kind: ENC[AES256_GCM,data:bs7Iny2Q,iv:Ww0ExY5SCtTVtaWlWdOUvcBBXMRGY9MUFtA+K63DMZM=,tag:GNnzff11i7wqEVFDfY5Adg==,type:str]
preferences: {}
users:
    - name: ENC[AES256_GCM,data:ziLFnZ5tBw==,iv:bwhR/smruTqriQBnHx6n/3ifghxihyLYaIiCjyA5TJs=,tag:voOg5YunOMO8llio3ObI1Q==,type:str]
      user:
        client-certificate-data: ENC[AES256_GCM,data:V/EUx4OFOJmvhhwjHThiCNg6Wo0DJ8tCs+fTFnkzF731o1oSNTtSvbXkG/xEjiTQWdd0lQ7TKVzxEowBYivOZlz5dOrytTrZoNK1ICljHlbpUNST2W4CV+B7sVYkMdH+Ibqlw9rHE/ZTSX7eSFVoxxRwcU/Knk5y/wI+NO/4x+vTBS+/1X7UQO5vJjX5cYNp+N4JLtyqtNLB4D340B94PkWcS8Vl9fSHhZlzpuLrifIbdj6HHc8jdiBee9zoq5xicnPFx6Fq0/+Hz6By8/AdQkXMFUiwg+aDs498QXNTc5+PEgY8NF036pcRa4WLQuCA1bGLh397VBv37jToV98OaecuO1KZHbQYWHtkJo3WZH+nfUdlHHRfbYEbEYRHGDiZtv48T7AoDSmW8LAcaKlm52rXKTneFYmbU/7Lmen40rRwKkUnRXepBSd9gy/Q9x1wmxo7byV1yaLDaQM8Y27ietOSv1qqhILLkHTybvOeQpjo1z2Kw2Z6P6gpKdsc+6XoQp+cyuGE5u5DulwZu84J21XZ6dmRF0ycyf9/y2+wo6O4d8s6Q32s/DZOTKdgT3l0e1n4Qa2No+i2lsZ8V3tbGMPgmA6s8sN7apVXABmbZbKjzChOFNNoDjx87HixWCtMlcuDP9u5teS0wjS7vRLIZzgcwGeNTnYsjBmutYwZon8sXJC6kRldDbDNSbNv/h1OvLUm58OmS6iWJiU/6XvxNuOgZFI+nBGEnROkDUwj/NqJM09GOr8MujimGgi3qdbUjr596dpU2At+Gs80FzQTCCzelZfHaUjmY/YpoO8flAWv0KXVUC8/Z+mSWfFyY8fy9meWW3W0EF3MA9lEEkLg0o3A6i7lCxz0h36Kyn4a9YkTn9WqSMZ0fks706/D/7TquZK/XrhciYj6zhbju7qrvZKflMlLG6aGskhCUyRFOnLtiZ6fG39lZooOpkzuIYEyL1anH3qSxV2rXX5MpTY0BnSj/9qibyXyX8krYd4NecpEDsXRLEeqmVkYCK2Yt6rGWjjO/Vnl1/zOBEgoaK8dk3uDNJ6q/VI1yVzT8Bpa4J85kQt6yyU7VjkcjV6MNBnA+2PV+1+TMWS1+VLhrThNeIGbKHhAC2X2ueYxjPV0BKYMa13ja3Rw4nQxVM2IsOpHFRcpXtdIFqQutE8pPPkN6Gku2wQNEa+oUhTKsx5I4Qsu34WiIt844j7uRdFI9YQjuvgFh1njxHT3jHlbGcExcTr3p9xzYY2ulGe3658BI2VbqbhcVv+SN0YcPzNurtRLUDN3rU7YNT8X5jXy6U33ksSg3YX9P0mEKFpzZv3MrYCJMk7o3/GIXjx2OiFTKuOCwQ8iaoMqpFLtwW0044uL+1iNUm43l+4jWWkiZLBXL6xT/fbnypHVAtgVenEzUag3l9HWOuyCFTagLTP7heGrONLdx7vfeiRHb3wZ8EcHMswLqidl0kX0pbPNZj/3XK5oAWzesP0tlXSedV08jRc6hds+bTv8cGVUYnmxnptXtE96gJguLW6uYDbXMD3wWe+ctDEKVVEks5h3XPiULGxeY9L0/Zyhh/UgvrlYxrzbagHK1aAObDZ7x+6dxUHbX9UtHw6BbWM3FYWRcF6beO8oeLjldbFOvziPskTe9vKUI1PWp00jIHFjeN5CkPnneI6AHQQUmUDoFX6mW3s5d8GsLP6sViPd4YGVg6z7P8tLTKrwWSsKts1WjqDLwAYGV5YM1kpB55kOidYXknYZmhbldv0Lnkq4Oh+CDDaYtuBIrrRV54hFUAgYvyIFxWPMgNawXkPo70Juwtjo8CC08AQrrUx6pPxyP/WFwEZivtzR7QeR6hBR1YOSdI3X9mBNQ5F32S520cVkKNrr0IzpBxJR1uXamAOKn4KsJQrbD0QJhl5hPu9U9bEJd/IEWGVCc/e0kn0KKXkCGeZsNBkuDbnvBpeNOJEs4KK0Tl0JLrcLJj3V+LOSLfWLucf1xnChVw/5BS5AJZWisPwtSA6E/RUxhjO4WwL7+juKMx86nfWHvo08wch+bCCODV/AS5ZHRiUQTQe6d5zlV2q2JYQhh4+lq0I6Zc6T99vY1avgkw==,iv:B513KXLOHlGMTm2lU791ew9xeSdHGfYFFNHfD7wzd7E=,tag:JBEisiENTvU12I81qf/sPw==,type:str]
        client-key-data: ENC[AES256_GCM,data:MrW8FFWPID0zP8DOC0mn8JzS+5Gp83mcvqA1T3+2q/cK3iShVaYpA4X36Z1dOkKh4kjpnWATmaJIZetrPWS95OYglmdaqryIU7XopWwZB6SfFLZkC+DPP2m9nbR/3IVBYQ9nO+xQZ3eqw1VLX7xgcU6a8ebCEKKXzlbWCUWB0/YAg1//x9POf5YbvIM5JGXbWj784nhJoOizyYGNMXPtGv2dDh5oYNZpAylotlBwg5hXk+iN1HAmMTRafgyVsSqzojWjsz2qmSN3GWQU7gVtZ5z7iOzZPKb6mt43sKBu0hZx0ee0iAVWNCPnxNMw8+kXP+/lFk19S6o8Nb/NkqA0mimrpMbOHH2YGBdjaCjkE6jQAq8wQJY2p6kqw1VRNfTXuxtFCzJdRpLrIWYghs0n1Q==,iv:bazacLuiyBKA+VGhjBBHnbZiHj62dyAm8Cr+kr+/1SI=,tag:f0LRRc0erRmWHRO0cE2hAQ==,type:str]
sops:
    age:
        - recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VzJRalF2YjVJVE11Qk8v
            N1hKS2dNNnM0Vno4ekpIc2lmS1NVNUlmb0VnCjM0ZnlHZzZaZkJmQzEvWVdQclI2
            Mmx6YzNHRUhnRzhFcUFzejloQjZJN28KLS0tIEpuUmhXZTBuS3JqQ2tqa2Vkczhx
            VWhvWU42d09wY0RXelpkcFFUQ0twUWsK0cyC+/tnFZCLbHzl/ZCWPJmGUqKj1nrR
            nbeGbQ70tSC7vT39S8k05yT2qUv3pqjOj2jxMrLUFBH2Y008YMP37g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcExvYkV4M3lQTHFCTVlF
            d1A4MUFzMHc0TGdIVUtCS3hmSXBlRFBGcWs0CmNDVDdXTGZybk5TVkhCeWg2eDNN
            OEY1MXdkdGd4WWNJSmhIUEsvZGRHY0UKLS0tIGdjbnZ6Z2I1T0JLVnduc281TVlY
            NjN1YTl4eDRNUFUwQ0NBMDNCL0paZG8KcMpMEBICp5ZEZQHm3d4RxJbfDUw870gr
            LQ+uLnmCYdMMPZfcTyQyfHqvsVbEFlQnSQko8jhM95UbbjE47l15Vg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ueu6gg5sgnvlnyk0u8zfyvpgrgja3g0xxdp9whegwk5rqlu42gjsveqrjj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQVN0SG1EZHVjaUY1ZmJR
            YnAvTS9ZN2s4aXN2a0V4NXNEci9vcmEwREZ3CmJYaTZIcFNYY3VnODZtSGcvcSsx
            dmZQRmRtQkZGbWdLRTVkQVpTNStZcjgKLS0tIG1QdGhiMm5lUDFYUWc4TDlrT1Zl
            NVBjZDd0MU5tb0hrRUdaVUMvOXVteU0KIUoHplHVco+qUp4HyzOOpItQ94SfGwKZ
            Wt3tunooRE9fgDKQT4haecjlY4vNoU35vOeyV1CppSPAiWMMdQgg4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1evyhf8qvcvftzhrznv65a6shag2r05wnzmfkfaad5l66ztztv4qsh7f23k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU0djUkpEVGU5TFIwZ2Jn
            dkJ0VGl1QWcyNURDeE9kb2tmVnNNZWFkcjJRCjF0cERsT2xWNzlXOXpOMjhSU0Z1
            M25uaVdEalRaMXFhbW1hUU1kZytYMUUKLS0tIE83Ykl0cDYvcVVmWE5DWnA5MWN3
            Q2M2d0pOd2VabFlUdEpGMjZCSnVnWG8KAiIjyu8nWS3jXw38cTb8DAkzApl0klmk
            imbcbA9riAD/ugwxZVUoxV0Nyp5dXzM8FivHC05BmpNFY2xNEyVedg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g22rh8x48tanpl5pq6pjrpmslnvv0e3qcm6w7dghhe8cnl5y0evqu835qm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YXoxeEkrRzU2c0dwUHJL
            bUZ5VTFjak1KbzhlbVNjZTlYMlhiZnFEU0RNCi9STm5IMytKdW9TaldHb3dvY3RV
            UjlSZlFwUFlTQnhhNjE2c0hqUnhZWkkKLS0tIGN2MkxQMFZ1R1RDZ2xVYng2eGRv
            OTJOamQ5eXdSSFVnMnZjWlpzUmQ4dHMKI2o/L6UhmocmwBb7vuM9peiDAvaz84jD
            qFBToEkU5/wlVjUM6l/DCMs2e+C1LQijXcXRqG8GV8rCSV4VdL7ryg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T10:20:51Z"
    mac: ENC[AES256_GCM,data:Y3nCsCQgWuUcWDaRdIM5qpJW+e8PNjoYP2lziHP6DwtIX09KXIJ149dRPkAtlLi8YMl0HywvMOJzFpLHu+SF6Uw1kdg3bN4PAu7LEAee5ZBSnn82Jd0U2cN1F93eGMvjPdw/wQHxHjicmAS/zqs/lRK9/tlahqnI3WACs6SZd18=,iv:P4b0fIBNPyXLh8J3ZC7QkYv627P6CugbbD7dCj32+hQ=,tag:4CHA6mZHLg8ZIF0RKM5LGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
