keel:
    slack:
        token: ENC[AES256_GCM,data:7Ytb0TUjgeX/HKDdsZ1/ICpZhAqgQbjbHKma+C7fsiMPAya8ZF7itWbCj8N47GRlayeIpDdbblq5,iv:yssXUeOf4BNu7ycBUcft1/hY2r+GsLl8v2Ag2EMoqN4=,tag:lmNdgNaOgG7lSN7YLXwJSA==,type:str]
sops:
    age:
        - recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBakp1VldsbnJIcUZRRlVB
            OEpiNy92NmMwaWRpd1FxK2ZKTHZ0RWpCOFNrCnFRRVdlNXIwRkhKemxodXhrOUZX
            ZDl2cmw3VitKcElHaExWUXNxSXN1MlkKLS0tIDk3RU1vdG5ESk1TUlNUZkJ0Zit4
            MTJjd09Td3RmaFozS2V6Uk9SNVdIdjgKcbQtskDnsW5teFwYxIK+XA8+38qtMc4w
            tmi1KUBWAn4FLJ72iXK4eCp6DPozaj7mQk17XluUvP3P2oN1jNM+qQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUnVnV0xna3grS3l4bVAr
            UXdSNnh2d2VJTzFZWkJBdHB5Q3RhU3E2d0YwCmhEenVyZ3dkcHVvOFBWdUhQSDU2
            NGdyZ2pmZkZ4OHJkYlN2YU44b0FWWmsKLS0tIHFUdmNpOUh3TlJMQitOZWZhUCsv
            bFpiNHIwM0dpZVRuWjM4NENGSkQ4RUUKtZjD4MqVHeZ4x620Q7JAB5gvlaYlOIGc
            yEsWiMqteJYme8ndnWGYeR4LhL4A2QRZcBkl5vAcoOvK5bzAto6d1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ueu6gg5sgnvlnyk0u8zfyvpgrgja3g0xxdp9whegwk5rqlu42gjsveqrjj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVDZQM2dxcEsyRk9wblRT
            R3ZrbTlMVlNTN2hVK29zVnc3QTBZWXIwR0FZCk4rYng4SWZXRmZBNS9raDAvNDhD
            V2xlb2dLakdzdUY3T2NQdmJRTEZMSzQKLS0tIDRTUnp1WFV3WUx0NkJZNGhueUJD
            VGJVVDhkc29uVFFFZDVvSE9VeXB3ODQKAs9FCkl6Z5gS3mQNOGVGGDzIF3H8KjKj
            Bwl1PFCloWBSwC6fy72hrmqOfGdQgPpracmtO2LB3vjV+BjQpYILlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1evyhf8qvcvftzhrznv65a6shag2r05wnzmfkfaad5l66ztztv4qsh7f23k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NzJtTDJBT2pqL1B6ZVJY
            U0JsU0ozelZwNnhIL0xzVnlTYUlTblhVQ2lFCi9XelEvZG1HbjhvaGVnam41ZUxQ
            Q1FiOUhlakRYK0w5NXc4Wjk5ZUFwdDgKLS0tIHVmbTk4cUY1RUwyU1gxKzliVHpB
            SkFZQ2tMdFo4aXF3NHJBNzRTZjd4VjAKDj2/7u+wb1fR+KSd1H80ioHdnf4tYw3z
            46Vn3T1qC0VYU8FMrRO9oGObNFcZJLw5jNZ8DD9k6GE+hecqQ8EUbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age138ut93gvvwkaudl3wxtwn8z9e50ptuhe2yukg6vhwcgncxpplpsqtmhp7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSzhHQ1F1cWpLZ3IrdFFH
            QzJHQytENVlWWHEwZkJTTGd6WjI5RTFVUDFzCjhEcXpuTWR5UEg2QjVTRitmaGxw
            TXpKVXFsdlNBWlFPREhFZVRhZnNGUzQKLS0tIFloRHNxTlFpMHRrQ3l5RnB4UGdD
            L1BFL0x5THVncG5RV3RONGZmWUlVT2sKI/TfZ5zwrQh7gMFtyiIHnE5UxjpXqVq2
            7rcVuSfSS66cMEgeIUeKX2eeAeGgSYysn9jFHT9IgUZT0jjii7dPxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T15:00:19Z"
    mac: ENC[AES256_GCM,data:2Ry7FeopDWwBOXXtpgEvcUCBHpmBwZr24frgp2Vi+E0BElYwaBohve+rgG4lPCuWaiw9guC1GSKRazQqVNp9ZVVBpFVs2ZmQX8F9ab3VwtKlJO1oNsd/XSPgRtHOYlzs340re440qAwFBNIINTOIfgxD5/J93Gu6wdPwNkbDgXI=,iv:nRE9ewJzTiZczWpLIeLqCyHCr2IbgqBO69g+BLwllI0=,tag:Agis5y3a9TwHeUGRGK2CFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
