keel:
    slack:
        token: ENC[AES256_GCM,data:7Ytb0TUjgeX/HKDdsZ1/ICpZhAqgQbjbHKma+C7fsiMPAya8ZF7itWbCj8N47GRlayeIpDdbblq5,iv:yssXUeOf4BNu7ycBUcft1/hY2r+GsLl8v2Ag2EMoqN4=,tag:lmNdgNaOgG7lSN7YLXwJSA==,type:str]
sops:
    age:
        - recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbktFNW94SDJONDVxbXBC
            ZHNCWXk3Y1JNSm1POTVNeEhJQ1F4NjUwZ1NBCkF1OERyMXdlSzJvQTZwNnhBR3BV
            T2xGblI4aFY3UjNpY2xFZjlxeWd0ZE0KLS0tIDRiUS9zdSs4azRJWGJiV0owalAw
            ek9zdXhEN0czOGlrY0d2cVVPSUl0UjQKMW/+nznaKLNsZjHv9gogwJYIRAwdhT5o
            9P91+pDt3lKMrffcAVodfXkViJGjgUIPpdBt38omDm2p85VsJ8DJPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUy9hOXRhVk42UFBJaWhC
            a1FtVmNpbk54TFpBQkhEbi8xTGsvMEdYYUNZCjVvTkpZbHpzQmVUZDMrczBaS043
            bWtPaHNjUzB4dm04cUlVUDJmbDlaRTAKLS0tIEZZcmpwSUZxM1Y5WHczVFduU2E0
            MlNnNTVUL2RBTi9BNEZNQUdaeHVod2sK324uQ0g6bW8Hk88Zl6k34M+YjPrwdJyY
            JsksrMZ+pmFb4rdJXgC5xRk+y+u0Bg+Q+si4ZkEhkLD0/wql/pL1AQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ueu6gg5sgnvlnyk0u8zfyvpgrgja3g0xxdp9whegwk5rqlu42gjsveqrjj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXNYK3ZjYWpQMzRjSkU1
            QVRyTW4rRzQ5ak05KzVpYldyckFWQjJmSUVnCnNqc2tmVHJFNnlOb3ZUcTJvdlFp
            cHM1UEpKQlNvVjF6OWdjRUFxZWtRQ0EKLS0tIDF5bDFCQVpsN2xXUTB6Q2lBa05D
            VjhaYjdGN21XWGJMeCtseG5iS1Y0dEEKyFlvLJa+mirQ9/xT19saQaq5YS7gLIdl
            VfRfWIBlfYBufCBxnU4TTNDaKAwUq65i3+0P2UIwMtP+YzgQDHWyhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1evyhf8qvcvftzhrznv65a6shag2r05wnzmfkfaad5l66ztztv4qsh7f23k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyc1ZLa1FMaDN1bEw1dEw5
            L1RKYjhDcmxGNENXbkZBdlF5SzFXME5rMnhZCkZQTnh5dTVNK1VhVDg5ejJGSHls
            YSs4eUtqNmRUNlNScll2blhZYWhNZXMKLS0tIERxa1dMYlpiMjBpS0NXUEgxZEpM
            YitTYk1BdkhpNjkvd0V1VW5CZ2s0bUkK2h4DZX4J+TdQzRFnb/TJdjuxLzCC7/Jc
            9vcEiABQ+vbWNk70qznUEx07yq8ZOYQO74UtiN3xqOWOF82WP1ZMBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g22rh8x48tanpl5pq6pjrpmslnvv0e3qcm6w7dghhe8cnl5y0evqu835qm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRlBoVllQNHUzd0J0RTBJ
            SG1EdUU5ZEEwWVEyS2J6eVN2NHVjTndPRlNrCjdvVlpzdXc2NDNWb2JJZU5wS1Bt
            bCsrYzRCb3ZRNXlQWXJsUE96ZEtYUzAKLS0tIExlNGg4NnVCS2ZkNVdPQmZWYk51
            aU93cDJGS3pOdmFmKzRudFFkaUlNUkEKWYhEbbXT/l2SV1oCQhMpzGWmgFhAL2Ja
            8uRNszv8SGP4II8eqR/kfHd0mKeo7vYzUuiw7qY/6oiOX8aaP7PsLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age138ut93gvvwkaudl3wxtwn8z9e50ptuhe2yukg6vhwcgncxpplpsqtmhp7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByV05XN0ovTFVSUy9qcW03
            MVAwQUJJSE9ic1djdjJOaWRGMENrSnhHNFhNCnhSTG1KdnRUZlg5SFU5WDVUMGtt
            MVk4RTdjeW56dXZxNno2Rjdld2VJN2sKLS0tIHU1SmY4T0tGTnJXZXVDeE81ZlNE
            TW80cFViSEdjUDFGMWdiQmNqTFVIWW8KsMiD34MewOnPxQfFVcPDwKQ+ZSoM/yxh
            xFc4njG2p9CeZXNXAUxfnsxgDWfKnfuYnpU2IYPf1s3sDWoK9uGpjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T15:00:19Z"
    mac: ENC[AES256_GCM,data:2Ry7FeopDWwBOXXtpgEvcUCBHpmBwZr24frgp2Vi+E0BElYwaBohve+rgG4lPCuWaiw9guC1GSKRazQqVNp9ZVVBpFVs2ZmQX8F9ab3VwtKlJO1oNsd/XSPgRtHOYlzs340re440qAwFBNIINTOIfgxD5/J93Gu6wdPwNkbDgXI=,iv:nRE9ewJzTiZczWpLIeLqCyHCr2IbgqBO69g+BLwllI0=,tag:Agis5y3a9TwHeUGRGK2CFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
